import '@fontsource/material-symbols-outlined/400.css';
import './styles/reset.css';
import './styles/tokens.css';
import './styles/motion.css';
import './styles/theme.css';
import './styles/layout.css';
import './styles/feedback.css';
import './components/material';
import './app-shell';
